# FIXME: WIP
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: nextjs-pipeline-run-
spec:
  serviceAccountName: nextjs-bot
  params:
    - name: app-name
      value: nextjs
    - name: source-repo
      value: https://github.com/cloud-native-garage-method-cohort/emea-8-bernhard-ott-nextjs-app
    - name: commit-sha
      value:
    - name: image-repo
      value: quay.io/bott_ibm/nextjs
  pipelineRef:
    name: nextjs-pipeline
  workspaces:
    - name: shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: gitops-repository
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 1Gi
          accessModes:
          - ReadWriteOnce
    - name: git-credentials
      secret:
        secretName: git-credentials
